example_app/urls.py
from django.urls import path
from example_app.views import index

app_name = 'example_app'

urlpatterns = [
    path('', index, name='index'),
]

project_django/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('example_app.urls')),
    path('wishlist/', include('wishlist.urls')),
]

wishlist/urls.py
from django.urls import path
from wishlist.views import show_wishlist
from wishlist.views import show_xml
from wishlist.views import show_json
from wishlist.views import show_json_by_id

from wishlist.views import register
from wishlist.views import login_user
from wishlist.views import logout_user

from wishlist.views import show_ajax
from wishlist.views import submit_ajax

app_name = 'wishlist'

urlpatterns = [
    path('', show_wishlist, name='show_wishlist'),
    path('xml/', show_xml, name='show_xml'),
    path('json/', show_json, name='show_json'),
    path('json/<int:id>', show_json_by_id, name='show_json_by_id'),
    path('register/', register, name='register'),
    path('login/', login_user, name='login'),
    path('logout/', logout_user, name='logout'),
    path('ajax/', show_ajax, name='show_ajax'),
    path('ajax/submit/', submit_ajax, name="submit_ajax"),
]

example_app/models.py
from django.db import models

# Create your models here.

wishlist/models.py
from django.db import models

# Create your models here.
class BarangWishlist(models.Model):
    nama_barang = models.CharField(max_length=50)
    harga_barang = models.IntegerField()
    deskripsi = models.TextField()

example_app/views.py
from django.shortcuts import render

def index(request):
    return render(request, 'index.html')

wishlist/views.py
from django.shortcuts import render
from wishlist.models import BarangWishlist

from django.http import HttpResponse
from django.core import serializers

from django.shortcuts import redirect
from django.contrib.auth.forms import UserCreationForm
from django.contrib import messages
from django.contrib.auth import authenticate, login
from django.contrib.auth import logout
from django.contrib.auth.decorators import login_required

import datetime
from django.http import HttpResponseRedirect
from django.urls import reverse

# Create your views here.
@login_required(login_url='/wishlist/login/')
def show_wishlist(request):
    data_barang_wishlist = BarangWishlist.objects.all()
    context = {
    'list_barang': data_barang_wishlist,
    'nama': 'Salma Hanifah Hidayanti',
    'last_login': request.COOKIES['last_login'],
    }
    return render(request, "wishlist.html", context)


def show_xml(request):
    data = BarangWishlist.objects.all()
    return HttpResponse(serializers.serialize("xml", data), content_type="application/xml")

def show_json(request):
    data = BarangWishlist.objects.all()
    return HttpResponse(serializers.serialize("json", data), content_type="application/json")

def show_json_by_id(request, id):
    data = BarangWishlist.objects.filter(pk=id)
    return HttpResponse(serializers.serialize("json", data), content_type="application/json")


def register(request):
    form = UserCreationForm()

    if request.method == "POST":
        form = UserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            messages.success(request, 'Akun telah berhasil dibuat!')
            return redirect('wishlist:login')
    
    context = {'form':form}
    return render(request, 'register.html', context)

def login_user(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(request, username=username, password=password)
        if user is not None:
            login(request, user)
            response = HttpResponseRedirect(reverse("wishlist:show_wishlist"))
            response.set_cookie('last_login', str(datetime.datetime.now()))
            return response
        else:
            messages.info(request, 'Username atau Password salah!')
    context = {}
    return render(request, 'login.html', context)

def logout_user(request):
    logout(request)
    response = HttpResponseRedirect(reverse('wishlist:login'))
    response.delete_cookie('last_login')
    return response


@login_required(login_url='/wishlist/login/')
def show_ajax(request):
    data_barang_wishlist = BarangWishlist.objects.all()
    context = {
    'list_barang': data_barang_wishlist,
    'nama': 'Salma Hanifah Hidayanti',
    'last_login': request.COOKIES['last_login'],
    }
    return render(request, "wishlist_ajax.html", context)

def submit_ajax(request):
    if request.method == 'POST':
        newItem = BarangWishlist(
            nama_barang=request.POST.get('nama_barang'),
            harga_barang=request.POST.get('harga_barang'),
            deskripsi=request.POST.get('deskripsi'),
        )
        newItem.save()
    return HttpResponseRedirect(reverse('wishlist:submit_ajax'))

example_app/templates/index.html
{% extends 'base.html' %}
{% load static %}

{% block meta %}
<title>Hello, world!</title>
{% endblock meta %}

{% block content %}
  <h1>Hello, world!</h1>
  <h3>This is example app for Django template</h3>
{% endblock content %}

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link rel="stylesheet" href="{% static 'css/style.css' %}">
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-iYQeCzEYFbKjA/T2uDLTpkwGzCiq6soy8tYaI1GyVh/UjpbCx/TYkiZhlZB6+fzT" crossorigin="anonymous">
  {% block meta %}
  {% endblock meta %}
</head>

<body>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-u1OknCvxWvY5kfmNBILK2hRnQC3Pr17a+RTT6rIHI7NnikvbZlHgTPOOmMi466C8" crossorigin="anonymous"></script>
  {% block content %}
  {% endblock content %}
</body>

</html>

wishlist/templates/login.html
{% extends 'base.html' %}

{% block meta %}
<title>Login</title>
{% endblock meta %}

{% block content %}

<nav class="navbar" style="background-color: lightgreen;">
    <div class="container-fluid">
      <span class="navbar-brand mb-0 h1">Salma Hanifah Hidayanti</span>
    </div>
  </nav>

<div class = "login">

    <h1>Login</h1>

    <form method="POST" action="">
        {% csrf_token %}
        <table>
            <tr>
                <td>Username: </td>
                <td><input type="text" name="username" placeholder="Username" class="form-control"></td>
            </tr>
                    
            <tr>
                <td>Password: </td>
                <td><input type="password" name="password" placeholder="Password" class="form-control"></td>
            </tr>

            <tr>
                <td></td>
                <td><input class="btn login_btn" type="submit" value="Login"></td>
            </tr>
        </table>
    </form>

    {% if messages %}
        <ul>
            {% for message in messages %}
                <li>{{ message }}</li>
            {% endfor %}
        </ul>
    {% endif %}     
        
    Belum mempunyai akun? <a href="{% url 'wishlist:register' %}">Buat Akun</a>

</div>

{% endblock content %}

wishlist/templates/register.html
{% extends 'base.html' %}

{% block meta %}
<title>Registrasi Akun</title>
{% endblock meta %}

{% block content %}  

<div class = "login">
    
    <h1>Formulir Registrasi</h1>  

        <form method="POST" >  
            {% csrf_token %}  
            <table>  
                {{ form.as_table }}  
                <tr>  
                    <td></td>
                    <td><input type="submit" name="submit" value="Daftar"/></td>  
                </tr>  
            </table>  
        </form>

    {% if messages %}  
        <ul>   
            {% for message in messages %}  
                <li>{{ message }}</li>  
                {% endfor %}  
        </ul>   
    {% endif %}

</div>  

{% endblock content %}

wishlist/templates/wishlist.html
{% extends 'base.html' %}

{% block content %}

<nav class="navbar" style="background-color: lightgreen;">
    <div class="container-fluid">
      <span class="navbar-brand mb-0 h1">{{nama}}</span>
      <a class="btn btn-outline-success" type="submit" href="{% url 'wishlist:logout' %}">Logout</a>
    </div>
  </nav>

<!--<h5>Nama: </h5>
<p>{{nama}}</p>-->

<table class = "table table-bordered w-auto" style="margin-left:auto; margin-right:auto; margin-top:25px;">
    <thread style="background-color: cyan;"></thread>
    <tr>
    <th>Nama Barang</th>
    <th>Harga Barang</th>
    <th>Deskripsi</th>
    </tr>
    {% comment %} Tambahkan data di bawah baris ini {% endcomment %}
    {% for barang in list_barang %}
        <tr>
            <th>{{barang.nama_barang}}</th>
            <th>{{barang.harga_barang}}</th>
            <th>{{barang.deskripsi}}</th>
        </tr>
    {% endfor %}
</table>
<h5>Sesi terakhir login: {{ last_login }}</h5>
<!--<button><a href="{% url 'wishlist:logout' %}">Logout</a></button>-->

{% endblock content %}

wishlist/templates/wishlist_ajax.html
{% extends 'base.html' %}

{% block content %}

<nav class="navbar" style="background-color: lightgreen;">
    <div class="container-fluid">
      <span class="navbar-brand mb-0 h1">{{nama}}</span>
      <a class="btn btn-outline-success" type="submit" href="{% url 'wishlist:logout' %}">Logout</a>
    </div>
  </nav>

<table class = "table table-bordered w-auto" style="margin-left:auto; margin-right:auto; margin-top:25px;">
    <thread style="background-color: cyan;"></thread>
    <tr>
    <th>Nama Barang</th>
    <th>Harga Barang</th>
    <th>Deskripsi</th>
    </tr>
    {% comment %} Tambahkan data di bawah baris ini {% endcomment %}
    {% for barang in list_barang %}
        <tr>
            <th>{{barang.nama_barang}}</th>
            <th>{{barang.harga_barang}}</th>
            <th>{{barang.deskripsi}}</th>
        </tr>
    {% endfor %}
</table>
<h5>Sesi terakhir login: {{ last_login }}</h5>

{% block meta %}
<script>
    function yaa(event){
        event.prevenDefault()
        $.post("/ajax/submit/"),
            {
                nama_barang : document.getElementById("nama_barang").value,
                harga_barang : document.getElementById("harga_barang").value,
                deskripsi: document.getElementById("deskripsi").value,
            }
        };
        return false;
    
</script>
<script type ="text/javascript">

    function refresh() {
        $.ajax({
            type: "GET",
            url: "/wishlist/json",
            dataType:"json",
            success: function(data){
                datanya = data
            }
        });
        return datanya;
    }
    function refresh2(){
        var datanya = refresh();
        var itemHtml = "<table> <tr> <th> Nama Barang</th>"
        for (var i =0; i<datanya.length; i++){
            var item = datanya[i].fields;
            itemHtml += '<tr> <th>' + item.nama_barang+ '</th> <th>' + item.deskripsi + '</th> </tr>';
        }
        itemHtml += "</table>";
        $('#lala').html(itemHtml);
    }
</script>
{% endblock meta %}

<h5>Nama: {{nama}}</h5>
<br>
<button onclick="refresh2()">get data</button>
<div id="Lala"></div>
<br>
<br>
<form method="POST" id="formnya" onsubmit="return yaa()">
    {% csrf_token %}
    <label for="nama_barang">Nama Barang:</label><br>
    <input id="nama_barang" type="text" name="nama_barang"><br>
    <label for="harga_barang">Harga Barang:</label><br>
    <input id="harga_barang" type="number" name="harga_barang"><br>
    <label for="deskripsi">Deskripsi:</label><br>
    <input id="deskripsi" type="text" name="diskripsi">
    <button type="submit">Submit</button>
</form>
<h5>Sesi terakhir login: {{ last_login }}</h5>
<button>Logout</button>

{% endblock content %}